spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/university
    username: postgres
    password: hossein
    initialization-mode: always
    hibenate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
        format_sql: true
    database: postgresql
    show-sql: true
    hibernate:
      use-new-id-generator-mappings: true
